name: fotowah_cmf
description: "CMF System App for Fotowat Al Aqsa"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Beiruti
      fonts:
        - asset: assets/fonts/Beiruti-Black.ttf
          weight: 900
        - asset: assets/fonts/Beiruti-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Beiruti-Bold.ttf
          weight: 700
        - asset: assets/fonts/Beiruti-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Beiruti-Medium.ttf
          weight: 500
        - asset: assets/fonts/Beiruti-Regular.ttf
          weight: 400
        - asset: assets/fonts/Beiruti-Light.ttf
          weight: 300
        - asset: assets/fonts/Beiruti-ExtraLight.ttf
          weight: 200
